# Generated by Django 5.2.17 on 2026-08-11 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('brand_name', models.CharField(blank=True, max_length=120)),
                ('business', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='waiting', max_length=20)),
                ('brand', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant', to='catalog.brand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
