[staging]
meowgang-store-staging ansible_host=172.31.8.77

[swarm_manager]
meowgang-prod-swarm-manager ansible_host=172.31.31.88

[swarm_workers]
meowgang-prod-swarm-worker-1 ansible_host=172.31.24.127
meowgang-prod-swarm-worker-2 ansible_host=172.31.21.241

[production:children]
swarm_manager
swarm_workers

[all:vars]
ansible_user=ec2-user